import type { LibraryExercise } from '../models/exercise'

function lib(e: Omit<LibraryExercise, 'source' | 'media'> & { placeholderToken?: string }): LibraryExercise {
  const { placeholderToken, ...rest } = e
  return {
    ...rest,
    source: 'library',
    media: { kind: 'placeholder', placeholderToken: placeholderToken ?? e.category },
  }
}

export const SEED_LIBRARY_EXERCISES: LibraryExercise[] = [
  lib({
    id: 'ex-barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'lower_back'],
    equipment: ['barbell'],
    instructions: [
      'Set the bar on a rack at upper-chest height and step under it, resting it across your upper back.',
      'Unrack the bar, step back, and set feet shoulder-width apart with toes slightly turned out.',
      'Brace your core, break at the hips and knees together, and lower until thighs are at least parallel to the floor.',
      'Drive through your whole foot to stand back up to full hip and knee extension.',
    ],
    techniqueTips: [
      'Keep your chest up and the bar path directly over your mid-foot.',
      'Push your knees out in line with your toes throughout the movement.',
    ],
    commonMistakes: ['Letting the knees cave inward', 'Rounding the lower back at the bottom', 'Rising onto the toes'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['back', 'forearms', 'core'],
    equipment: ['barbell'],
    instructions: [
      'Stand with mid-foot under the bar, feet hip-width apart.',
      'Hinge at the hips to grip the bar just outside your shins, back flat.',
      'Brace your core, pull the slack out of the bar, and drive through the floor to stand up, keeping the bar close to your body.',
      'Lower the bar back down by pushing your hips back first, then bending the knees.',
    ],
    techniqueTips: ['Keep the bar in contact with your legs on the way up.', 'Lock out by squeezing your glutes, not by leaning back.'],
    commonMistakes: ['Rounding the back', 'Letting the bar drift away from the body', 'Hyperextending at lockout'],
    placeholderToken: 'deadlift',
  }),
  lib({
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    instructions: [
      'Lie on the bench with eyes under the bar, feet flat on the floor.',
      'Grip the bar slightly wider than shoulder-width and unrack it over your chest.',
      'Lower the bar with control to your mid-chest, elbows at roughly 45 degrees.',
      'Press the bar back up to full arm extension.',
    ],
    techniqueTips: ['Keep your shoulder blades pulled back and down.', 'Maintain a slight arch and keep your feet driving into the floor.'],
    commonMistakes: ['Bouncing the bar off the chest', 'Flaring the elbows to 90 degrees', 'Lifting the hips off the bench'],
    placeholderToken: 'bench',
  }),
  lib({
    id: 'ex-overhead-press',
    name: 'Standing Overhead Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell'],
    instructions: [
      'Hold the bar at shoulder height with an overhand grip, elbows slightly in front.',
      'Brace your core and press the bar straight up, moving your head back slightly to let it pass.',
      'Finish with the bar over your mid-foot and arms fully extended.',
      'Lower back to the shoulders with control.',
    ],
    techniqueTips: ['Squeeze your glutes to avoid leaning back excessively.'],
    commonMistakes: ['Pressing the bar forward instead of straight up', 'Using excessive leg drive as a substitute for a strict press'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-barbell-row',
    name: 'Bent-Over Barbell Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: ['barbell'],
    instructions: [
      'Hinge forward from the hips to roughly 45 degrees, knees slightly bent, back flat.',
      'Grip the bar just outside your legs and let it hang at arm’s length.',
      'Pull the bar to your lower ribcage, driving your elbows back.',
      'Lower with control back to the starting position.',
    ],
    techniqueTips: ['Keep your core braced to protect your lower back.'],
    commonMistakes: ['Standing too upright', 'Using momentum to jerk the weight up'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-pull-up',
    name: 'Pull-Up',
    category: 'bodyweight',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    instructions: [
      'Hang from the bar with an overhand grip, slightly wider than shoulders.',
      'Pull your chest toward the bar by driving your elbows down and back.',
      'Continue until your chin clears the bar.',
      'Lower yourself back down with control to a full hang.',
    ],
    techniqueTips: ['Engage your lats before pulling to avoid shrugging.'],
    commonMistakes: ['Using excessive kipping/momentum', 'Not achieving a full range of motion'],
    placeholderToken: 'pullup',
  }),
  lib({
    id: 'ex-push-up',
    name: 'Push-Up',
    category: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: ['none'],
    instructions: [
      'Start in a plank with hands slightly wider than shoulders.',
      'Keep your body in a straight line as you bend the elbows and lower your chest to the floor.',
      'Press back up to full arm extension.',
    ],
    techniqueTips: ['Keep your core and glutes braced throughout.'],
    commonMistakes: ['Letting the hips sag', 'Flaring the elbows out to 90 degrees'],
    placeholderToken: 'pushup',
  }),
  lib({
    id: 'ex-dumbbell-lunge',
    name: 'Dumbbell Walking Lunge',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    instructions: [
      'Hold a dumbbell in each hand at your sides.',
      'Step forward into a lunge, lowering the back knee toward the floor.',
      'Push through the front foot to step through into the next lunge.',
    ],
    techniqueTips: ['Keep your torso upright and front knee tracking over the foot.'],
    commonMistakes: ['Taking too short a step', 'Letting the front knee cave inward'],
    placeholderToken: 'lunge',
  }),
  lib({
    id: 'ex-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    instructions: [
      'Sit or stand holding a dumbbell at each shoulder, palms facing forward.',
      'Press both dumbbells overhead until arms are fully extended.',
      'Lower back to shoulder height with control.',
    ],
    techniqueTips: ['Avoid arching your lower back excessively when standing.'],
    commonMistakes: ['Pressing unevenly', 'Flaring elbows too far back'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-plank',
    name: 'Plank',
    category: 'bodyweight',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['mat'],
    instructions: [
      'Rest on your forearms and toes, elbows under shoulders.',
      'Keep your body in a straight line from head to heels.',
      'Hold, breathing steadily, without letting the hips sag or pike up.',
    ],
    techniqueTips: ['Squeeze your glutes and brace your abs as if bracing for a punch.'],
    commonMistakes: ['Letting the hips sag', 'Holding your breath'],
    placeholderToken: 'plank',
  }),
  lib({
    id: 'ex-kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'functional',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['kettlebell'],
    instructions: [
      'Stand with feet shoulder-width apart, kettlebell on the floor in front of you.',
      'Hinge at the hips to grip the bell, then hike it back between your legs.',
      'Drive your hips forward explosively to swing the bell to shoulder height.',
      'Let it swing back down and repeat.',
    ],
    techniqueTips: ['This is a hip-hinge movement, not a squat or a front raise.'],
    commonMistakes: ['Squatting the movement instead of hinging', 'Using the arms to lift the weight'],
    placeholderToken: 'kettlebell',
  }),
  lib({
    id: 'ex-box-jump',
    name: 'Box Jump',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['other'],
    instructions: [
      'Stand facing a sturdy box, feet shoulder-width apart.',
      'Swing your arms back, bend the knees, then explode upward and forward onto the box.',
      'Land softly with knees bent, then step back down.',
    ],
    techniqueTips: ['Land in a stable, quiet position before stepping down.'],
    commonMistakes: ['Jumping to a box that is too high, compromising landing mechanics', 'Jumping back down instead of stepping down'],
    placeholderToken: 'jump',
  }),
  lib({
    id: 'ex-treadmill-run',
    name: 'Treadmill Run',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'calves'],
    equipment: ['treadmill'],
    instructions: [
      'Start at an easy walking pace to warm up.',
      'Gradually increase speed to your target pace.',
      'Maintain an upright posture with a relaxed arm swing.',
    ],
    techniqueTips: ['Land with your foot under your hips, not out in front of you.'],
    commonMistakes: ['Holding onto the handrails', 'Overstriding'],
    placeholderToken: 'run',
  }),
  lib({
    id: 'ex-stationary-bike',
    name: 'Stationary Bike',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'hamstrings', 'calves'],
    equipment: ['bike'],
    instructions: [
      'Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke.',
      'Pedal at a steady cadence for your target duration or distance.',
    ],
    techniqueTips: ['Keep a relaxed grip on the handlebars and avoid rocking your hips.'],
    commonMistakes: ['Seat set too low, causing knee strain'],
    placeholderToken: 'bike',
  }),
  lib({
    id: 'ex-rowing-machine',
    name: 'Rowing Machine',
    category: 'cardio',
    primaryMuscles: ['back', 'cardiovascular'],
    secondaryMuscles: ['hamstrings', 'biceps'],
    equipment: ['rower'],
    instructions: [
      'Drive with the legs first, then lean back slightly, then pull the handle to your ribcage.',
      'Reverse the sequence to return to the catch: arms out, lean forward, then bend the knees.',
    ],
    techniqueTips: ['Legs-body-arms on the drive, arms-body-legs on the recovery.'],
    commonMistakes: ['Pulling with the arms before the legs finish driving', 'Rounding the back at the catch'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['calves'],
    equipment: ['other'],
    instructions: ['Hold the rope handles at hip height and swing it using your wrists.', 'Jump just high enough to clear the rope with a soft landing.'],
    techniqueTips: ['Keep jumps small and stay light on the balls of your feet.'],
    commonMistakes: ['Jumping too high on each rep', 'Swinging the rope from the shoulders instead of the wrists'],
    placeholderToken: 'rope',
  }),
  lib({
    id: 'ex-hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['hip_flexors'],
    secondaryMuscles: ['quads'],
    equipment: ['mat'],
    instructions: [
      'Kneel on one knee with the other foot planted in front, both at 90 degrees.',
      'Squeeze the glute of the kneeling leg and shift your hips forward slightly.',
      'Hold, feeling a stretch in the front of the kneeling-leg hip.',
    ],
    techniqueTips: ['Keep your torso upright rather than leaning forward.'],
    commonMistakes: ['Arching the lower back instead of shifting the hips'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-shoulder-dislocates',
    name: 'Band Shoulder Dislocates',
    category: 'mobility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['chest', 'back'],
    equipment: ['resistance_band'],
    instructions: [
      'Hold a light band or dowel with a wide, overhand grip.',
      'Keeping your arms straight, raise it overhead and continue behind your back.',
      'Reverse the motion back to the front.',
    ],
    techniqueTips: ['Widen your grip if you cannot keep arms straight throughout.'],
    commonMistakes: ['Bending the elbows to compensate for a tight grip width'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'mobility',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: [],
    equipment: ['resistance_band'],
    instructions: [
      'Hold a light resistance band with arms extended in front at shoulder height.',
      'Pull the band apart by driving the shoulder blades together.',
      'Return with control.',
    ],
    techniqueTips: ['Keep a slight bend in the elbows throughout.'],
    commonMistakes: ['Shrugging the shoulders up toward the ears'],
    placeholderToken: 'band',
  }),
  lib({
    id: 'ex-cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    primaryMuscles: ['lower_back'],
    secondaryMuscles: ['core'],
    equipment: ['mat'],
    instructions: [
      'Start on hands and knees, wrists under shoulders, knees under hips.',
      'Inhale, drop the belly, and lift the chest and tailbone (cow).',
      'Exhale, round the spine, tucking the chin and tailbone (cat).',
    ],
    techniqueTips: ['Move slowly and match the movement to your breath.'],
    commonMistakes: ['Rushing through the reps without full range of motion'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['lower_back'],
    equipment: ['none'],
    instructions: [
      'Place one heel on a low surface with the leg straight.',
      'Hinge forward from the hips, keeping your back flat, until you feel a stretch.',
      'Hold, then switch sides.',
    ],
    techniqueTips: ['Avoid rounding the lower back to reach further.'],
    commonMistakes: ['Bouncing into the stretch'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-foam-roll-quads',
    name: 'Foam Rolling – Quads',
    category: 'recovery',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['foam_roller'],
    instructions: [
      'Lie face down with the roller under your thighs, supporting yourself on your forearms.',
      'Slowly roll from just above the knee to just below the hip.',
      'Pause on any tender spots for a few breaths.',
    ],
    techniqueTips: ['Keep your core engaged to control the roll speed.'],
    commonMistakes: ['Rolling too fast to feel any effect'],
    placeholderToken: 'roller',
  }),
  lib({
    id: 'ex-box-breathing',
    name: 'Guided Box Breathing',
    category: 'recovery',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    instructions: [
      'Sit comfortably and inhale slowly through the nose for 4 counts.',
      'Hold for 4 counts.',
      'Exhale slowly for 4 counts, then hold empty for 4 counts.',
      'Repeat the cycle.',
    ],
    techniqueTips: ['Keep the breath smooth rather than forced.'],
    commonMistakes: ['Breathing shallowly from the chest instead of the diaphragm'],
    placeholderToken: 'breathing',
  }),
  lib({
    id: 'ex-recovery-walk',
    name: 'Easy Recovery Walk',
    category: 'recovery',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['calves'],
    equipment: ['none'],
    instructions: ['Walk at a comfortable, conversational pace.', 'Focus on relaxed posture and steady breathing.'],
    techniqueTips: ['Keep the effort easy enough to hold a conversation throughout.'],
    commonMistakes: ['Walking fast enough that it becomes a conditioning session'],
    placeholderToken: 'walk',
  }),
  lib({
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbell', 'kettlebell'],
    instructions: [
      'Hold a dumbbell or kettlebell vertically against your chest.',
      'Squat down between your knees, keeping your chest up.',
      'Drive through your feet to stand back up.',
    ],
    techniqueTips: ['Let your elbows brush the inside of your knees at the bottom.'],
    commonMistakes: ['Letting the weight pull you forward', 'Not reaching full depth'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-plank-shoulder-tap',
    name: 'Plank Shoulder Tap',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['mat'],
    instructions: [
      'Start in a high plank with hands under shoulders and feet wide.',
      'Tap one hand to the opposite shoulder while keeping the hips as still as possible.',
      'Alternate sides.',
    ],
    techniqueTips: ['Widening your feet increases stability if the hips rock.'],
    commonMistakes: ['Letting the hips twist with each tap'],
    placeholderToken: 'plank',
  }),
]
