import type { LibraryExercise } from '../models/exercise'

function lib(e: Omit<LibraryExercise, 'source' | 'media'> & { placeholderToken?: string }): LibraryExercise {
  const { placeholderToken, ...rest } = e
  return {
    ...rest,
    source: 'library',
    media: { kind: 'placeholder', placeholderToken: placeholderToken ?? e.category },
  }
}

export const SEED_LIBRARY_EXERCISES: LibraryExercise[] = [
  lib({
    id: 'ex-barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'lower_back'],
    equipment: ['barbell'],
    instructions: [
      'Set the bar on a rack at upper-chest height and step under it, resting it across your upper back.',
      'Unrack the bar, step back, and set feet shoulder-width apart with toes slightly turned out.',
      'Brace your core, break at the hips and knees together, and lower until thighs are at least parallel to the floor.',
      'Drive through your whole foot to stand back up to full hip and knee extension.',
    ],
    techniqueTips: [
      'Keep your chest up and the bar path directly over your mid-foot.',
      'Push your knees out in line with your toes throughout the movement.',
    ],
    commonMistakes: ['Letting the knees cave inward', 'Rounding the lower back at the bottom', 'Rising onto the toes'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['back', 'forearms', 'core'],
    primarySpecificMuscles: ['gluteus_maximus'],
    equipment: ['barbell'],
    instructions: [
      'Stand with mid-foot under the bar, feet hip-width apart.',
      'Hinge at the hips to grip the bar just outside your shins, back flat.',
      'Brace your core, pull the slack out of the bar, and drive through the floor to stand up, keeping the bar close to your body.',
      'Lower the bar back down by pushing your hips back first, then bending the knees.',
    ],
    techniqueTips: ['Keep the bar in contact with your legs on the way up.', 'Lock out by squeezing your glutes, not by leaning back.'],
    commonMistakes: ['Rounding the back', 'Letting the bar drift away from the body', 'Hyperextending at lockout'],
    placeholderToken: 'deadlift',
  }),
  lib({
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    primarySpecificMuscles: ['chest_lower'],
    equipment: ['barbell', 'bench'],
    instructions: [
      'Lie on the bench with eyes under the bar, feet flat on the floor.',
      'Grip the bar slightly wider than shoulder-width and unrack it over your chest.',
      'Lower the bar with control to your mid-chest, elbows at roughly 45 degrees.',
      'Press the bar back up to full arm extension.',
    ],
    techniqueTips: ['Keep your shoulder blades pulled back and down.', 'Maintain a slight arch and keep your feet driving into the floor.'],
    commonMistakes: ['Bouncing the bar off the chest', 'Flaring the elbows to 90 degrees', 'Lifting the hips off the bench'],
    placeholderToken: 'bench',
  }),
  lib({
    id: 'ex-overhead-press',
    name: 'Standing Overhead Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    primarySpecificMuscles: ['front_delts'],
    secondarySpecificMuscles: ['triceps_lateral_head'],
    equipment: ['barbell'],
    instructions: [
      'Hold the bar at shoulder height with an overhand grip, elbows slightly in front.',
      'Brace your core and press the bar straight up, moving your head back slightly to let it pass.',
      'Finish with the bar over your mid-foot and arms fully extended.',
      'Lower back to the shoulders with control.',
    ],
    techniqueTips: ['Squeeze your glutes to avoid leaning back excessively.'],
    commonMistakes: ['Pressing the bar forward instead of straight up', 'Using excessive leg drive as a substitute for a strict press'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-barbell-row',
    name: 'Bent-Over Barbell Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    primarySpecificMuscles: ['lats'],
    secondarySpecificMuscles: ['rear_delts'],
    equipment: ['barbell'],
    instructions: [
      'Hinge forward from the hips to roughly 45 degrees, knees slightly bent, back flat.',
      'Grip the bar just outside your legs and let it hang at arm’s length.',
      'Pull the bar to your lower ribcage, driving your elbows back.',
      'Lower with control back to the starting position.',
    ],
    techniqueTips: ['Keep your core braced to protect your lower back.'],
    commonMistakes: ['Standing too upright', 'Using momentum to jerk the weight up'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-pull-up',
    name: 'Pull-Up',
    category: 'bodyweight',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    primarySpecificMuscles: ['lats'],
    equipment: ['pull_up_bar'],
    instructions: [
      'Hang from the bar with an overhand grip, slightly wider than shoulders.',
      'Pull your chest toward the bar by driving your elbows down and back.',
      'Continue until your chin clears the bar.',
      'Lower yourself back down with control to a full hang.',
    ],
    techniqueTips: ['Engage your lats before pulling to avoid shrugging.'],
    commonMistakes: ['Using excessive kipping/momentum', 'Not achieving a full range of motion'],
    placeholderToken: 'pullup',
  }),
  lib({
    id: 'ex-push-up',
    name: 'Push-Up',
    category: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: ['none'],
    instructions: [
      'Start in a plank with hands slightly wider than shoulders.',
      'Keep your body in a straight line as you bend the elbows and lower your chest to the floor.',
      'Press back up to full arm extension.',
    ],
    techniqueTips: ['Keep your core and glutes braced throughout.'],
    commonMistakes: ['Letting the hips sag', 'Flaring the elbows out to 90 degrees'],
    placeholderToken: 'pushup',
  }),
  lib({
    id: 'ex-dumbbell-lunge',
    name: 'Dumbbell Walking Lunge',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    instructions: [
      'Hold a dumbbell in each hand at your sides.',
      'Step forward into a lunge, lowering the back knee toward the floor.',
      'Push through the front foot to step through into the next lunge.',
    ],
    techniqueTips: ['Keep your torso upright and front knee tracking over the foot.'],
    commonMistakes: ['Taking too short a step', 'Letting the front knee cave inward'],
    placeholderToken: 'lunge',
  }),
  lib({
    id: 'ex-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    primarySpecificMuscles: ['front_delts'],
    equipment: ['dumbbell', 'bench'],
    instructions: [
      'Sit or stand holding a dumbbell at each shoulder, palms facing forward.',
      'Press both dumbbells overhead until arms are fully extended.',
      'Lower back to shoulder height with control.',
    ],
    techniqueTips: ['Avoid arching your lower back excessively when standing.'],
    commonMistakes: ['Pressing unevenly', 'Flaring elbows too far back'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-plank',
    name: 'Plank',
    category: 'bodyweight',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    primarySpecificMuscles: ['lower_abs'],
    secondarySpecificMuscles: ['obliques'],
    equipment: ['mat'],
    instructions: [
      'Rest on your forearms and toes, elbows under shoulders.',
      'Keep your body in a straight line from head to heels.',
      'Hold, breathing steadily, without letting the hips sag or pike up.',
    ],
    techniqueTips: ['Squeeze your glutes and brace your abs as if bracing for a punch.'],
    commonMistakes: ['Letting the hips sag', 'Holding your breath'],
    placeholderToken: 'plank',
  }),
  lib({
    id: 'ex-kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'functional',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['kettlebell'],
    instructions: [
      'Stand with feet shoulder-width apart, kettlebell on the floor in front of you.',
      'Hinge at the hips to grip the bell, then hike it back between your legs.',
      'Drive your hips forward explosively to swing the bell to shoulder height.',
      'Let it swing back down and repeat.',
    ],
    techniqueTips: ['This is a hip-hinge movement, not a squat or a front raise.'],
    commonMistakes: ['Squatting the movement instead of hinging', 'Using the arms to lift the weight'],
    placeholderToken: 'kettlebell',
  }),
  lib({
    id: 'ex-box-jump',
    name: 'Box Jump',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['other'],
    instructions: [
      'Stand facing a sturdy box, feet shoulder-width apart.',
      'Swing your arms back, bend the knees, then explode upward and forward onto the box.',
      'Land softly with knees bent, then step back down.',
    ],
    techniqueTips: ['Land in a stable, quiet position before stepping down.'],
    commonMistakes: ['Jumping to a box that is too high, compromising landing mechanics', 'Jumping back down instead of stepping down'],
    placeholderToken: 'jump',
  }),
  lib({
    id: 'ex-treadmill-run',
    name: 'Treadmill Run',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'calves'],
    equipment: ['treadmill'],
    instructions: [
      'Start at an easy walking pace to warm up.',
      'Gradually increase speed to your target pace.',
      'Maintain an upright posture with a relaxed arm swing.',
    ],
    techniqueTips: ['Land with your foot under your hips, not out in front of you.'],
    commonMistakes: ['Holding onto the handrails', 'Overstriding'],
    placeholderToken: 'run',
  }),
  lib({
    id: 'ex-stationary-bike',
    name: 'Stationary Bike',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'hamstrings', 'calves'],
    equipment: ['bike'],
    instructions: [
      'Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke.',
      'Pedal at a steady cadence for your target duration or distance.',
    ],
    techniqueTips: ['Keep a relaxed grip on the handlebars and avoid rocking your hips.'],
    commonMistakes: ['Seat set too low, causing knee strain'],
    placeholderToken: 'bike',
  }),
  lib({
    id: 'ex-rowing-machine',
    name: 'Rowing Machine',
    category: 'cardio',
    primaryMuscles: ['back', 'cardiovascular'],
    secondaryMuscles: ['hamstrings', 'biceps'],
    equipment: ['rower'],
    instructions: [
      'Drive with the legs first, then lean back slightly, then pull the handle to your ribcage.',
      'Reverse the sequence to return to the catch: arms out, lean forward, then bend the knees.',
    ],
    techniqueTips: ['Legs-body-arms on the drive, arms-body-legs on the recovery.'],
    commonMistakes: ['Pulling with the arms before the legs finish driving', 'Rounding the back at the catch'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['calves'],
    equipment: ['other'],
    instructions: ['Hold the rope handles at hip height and swing it using your wrists.', 'Jump just high enough to clear the rope with a soft landing.'],
    techniqueTips: ['Keep jumps small and stay light on the balls of your feet.'],
    commonMistakes: ['Jumping too high on each rep', 'Swinging the rope from the shoulders instead of the wrists'],
    placeholderToken: 'rope',
  }),
  lib({
    id: 'ex-hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['hip_flexors'],
    secondaryMuscles: ['quads'],
    equipment: ['mat'],
    instructions: [
      'Kneel on one knee with the other foot planted in front, both at 90 degrees.',
      'Squeeze the glute of the kneeling leg and shift your hips forward slightly.',
      'Hold, feeling a stretch in the front of the kneeling-leg hip.',
    ],
    techniqueTips: ['Keep your torso upright rather than leaning forward.'],
    commonMistakes: ['Arching the lower back instead of shifting the hips'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-shoulder-dislocates',
    name: 'Band Shoulder Dislocates',
    category: 'mobility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['chest', 'back'],
    equipment: ['resistance_band'],
    instructions: [
      'Hold a light band or dowel with a wide, overhand grip.',
      'Keeping your arms straight, raise it overhead and continue behind your back.',
      'Reverse the motion back to the front.',
    ],
    techniqueTips: ['Widen your grip if you cannot keep arms straight throughout.'],
    commonMistakes: ['Bending the elbows to compensate for a tight grip width'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'mobility',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: [],
    equipment: ['resistance_band'],
    instructions: [
      'Hold a light resistance band with arms extended in front at shoulder height.',
      'Pull the band apart by driving the shoulder blades together.',
      'Return with control.',
    ],
    techniqueTips: ['Keep a slight bend in the elbows throughout.'],
    commonMistakes: ['Shrugging the shoulders up toward the ears'],
    placeholderToken: 'band',
  }),
  lib({
    id: 'ex-cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    primaryMuscles: ['lower_back'],
    secondaryMuscles: ['core'],
    equipment: ['mat'],
    instructions: [
      'Start on hands and knees, wrists under shoulders, knees under hips.',
      'Inhale, drop the belly, and lift the chest and tailbone (cow).',
      'Exhale, round the spine, tucking the chin and tailbone (cat).',
    ],
    techniqueTips: ['Move slowly and match the movement to your breath.'],
    commonMistakes: ['Rushing through the reps without full range of motion'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['lower_back'],
    equipment: ['none'],
    instructions: [
      'Place one heel on a low surface with the leg straight.',
      'Hinge forward from the hips, keeping your back flat, until you feel a stretch.',
      'Hold, then switch sides.',
    ],
    techniqueTips: ['Avoid rounding the lower back to reach further.'],
    commonMistakes: ['Bouncing into the stretch'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-foam-roll-quads',
    name: 'Foam Rolling – Quads',
    category: 'recovery',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['foam_roller'],
    instructions: [
      'Lie face down with the roller under your thighs, supporting yourself on your forearms.',
      'Slowly roll from just above the knee to just below the hip.',
      'Pause on any tender spots for a few breaths.',
    ],
    techniqueTips: ['Keep your core engaged to control the roll speed.'],
    commonMistakes: ['Rolling too fast to feel any effect'],
    placeholderToken: 'roller',
  }),
  lib({
    id: 'ex-box-breathing',
    name: 'Guided Box Breathing',
    category: 'recovery',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    instructions: [
      'Sit comfortably and inhale slowly through the nose for 4 counts.',
      'Hold for 4 counts.',
      'Exhale slowly for 4 counts, then hold empty for 4 counts.',
      'Repeat the cycle.',
    ],
    techniqueTips: ['Keep the breath smooth rather than forced.'],
    commonMistakes: ['Breathing shallowly from the chest instead of the diaphragm'],
    placeholderToken: 'breathing',
  }),
  lib({
    id: 'ex-recovery-walk',
    name: 'Easy Recovery Walk',
    category: 'recovery',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['calves'],
    equipment: ['none'],
    instructions: ['Walk at a comfortable, conversational pace.', 'Focus on relaxed posture and steady breathing.'],
    techniqueTips: ['Keep the effort easy enough to hold a conversation throughout.'],
    commonMistakes: ['Walking fast enough that it becomes a conditioning session'],
    placeholderToken: 'walk',
  }),
  lib({
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    category: 'functional',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbell', 'kettlebell'],
    instructions: [
      'Hold a dumbbell or kettlebell vertically against your chest.',
      'Squat down between your knees, keeping your chest up.',
      'Drive through your feet to stand back up.',
    ],
    techniqueTips: ['Let your elbows brush the inside of your knees at the bottom.'],
    commonMistakes: ['Letting the weight pull you forward', 'Not reaching full depth'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-plank-shoulder-tap',
    name: 'Plank Shoulder Tap',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['mat'],
    instructions: [
      'Start in a high plank with hands under shoulders and feet wide.',
      'Tap one hand to the opposite shoulder while keeping the hips as still as possible.',
      'Alternate sides.',
    ],
    techniqueTips: ['Widening your feet increases stability if the hips rock.'],
    commonMistakes: ['Letting the hips twist with each tap'],
    placeholderToken: 'plank',
  }),

  // --- Cable and machine equipment (including Hammer Strength-style plate-loaded machines) ---
  lib({
    id: 'ex-cable-chest-fly',
    name: 'Cable Chest Fly',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    instructions: [
      'Set both pulleys to chest height and grab a handle in each hand, stepping forward into a slight split stance.',
      'Start with arms out wide, a soft bend in the elbows.',
      'Bring your hands together in front of your chest in a hugging arc, squeezing the chest at the finish.',
      'Return with control to the starting position, keeping the same elbow bend throughout.',
    ],
    techniqueTips: ['Lead with your hands, not your elbows.', 'Keep a slight forward lean and braced core.'],
    commonMistakes: ['Turning it into a press by bending the elbows more at the finish', 'Using so much weight the shoulders round forward'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-cable-tricep-pushdown',
    name: 'Cable Tricep Pushdown',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    primarySpecificMuscles: ['triceps_lateral_head'],
    equipment: ['cable'],
    instructions: [
      'Attach a bar or rope to a high pulley and grip with palms down (or facing in for a rope).',
      'Pin your elbows to your sides and start with forearms roughly parallel to the floor.',
      'Extend your elbows to press the attachment down until your arms are straight.',
      'Let it rise back to the start with control, keeping the elbows still.',
    ],
    techniqueTips: ['Keep your elbows locked at your sides throughout — only the forearm moves.'],
    commonMistakes: ['Letting the elbows drift forward or flare out', 'Using body weight/leaning to move the stack'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-cable-bicep-curl',
    name: 'Cable Bicep Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    primarySpecificMuscles: ['biceps_short_head', 'biceps_long_head'],
    equipment: ['cable'],
    instructions: [
      'Attach a straight or EZ bar to a low pulley and grip with palms facing up.',
      'Stand tall with elbows pinned to your sides.',
      'Curl the bar up toward your shoulders without swinging your torso.',
      'Lower back down under control to full arm extension.',
    ],
    techniqueTips: ['The constant cable tension means the top and bottom of the rep both stay loaded — resist the urge to rush either end.'],
    commonMistakes: ['Swinging the torso to sling the weight up', 'Letting the elbows travel forward'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    primarySpecificMuscles: ['lats'],
    equipment: ['cable'],
    instructions: [
      'Sit at the row station with knees slightly bent and feet on the platform, grip the handle with arms extended.',
      'Sit up tall with a neutral spine.',
      'Pull the handle to your lower ribcage, driving your elbows back and squeezing your shoulder blades together.',
      'Extend your arms back out with control, allowing a slight forward lean at the torso.',
    ],
    techniqueTips: ['Keep your torso mostly still — the pull should come from the arms and back, not from rocking.'],
    commonMistakes: ['Rounding the lower back at the start', 'Using momentum by rocking the torso'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-cable-face-pull',
    name: 'Cable Face Pull',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    primarySpecificMuscles: ['rear_delts'],
    equipment: ['cable'],
    instructions: [
      'Attach a rope to a high pulley, set roughly at face height.',
      'Grip the rope with palms facing in and step back to create tension.',
      'Pull the rope toward your face, flaring the elbows out wide and rotating your hands back at the finish.',
      'Return with control to the starting position.',
    ],
    techniqueTips: ['Focus on pulling with the rear shoulders, keeping the elbows high through the whole range.'],
    commonMistakes: ['Pulling low toward the chest instead of the face', 'Using too much weight and losing the external rotation at the finish'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    primarySpecificMuscles: ['side_delts'],
    equipment: ['cable'],
    instructions: [
      'Set a pulley to its lowest position and stand side-on to the machine, gripping the handle with the far hand.',
      'Start with the arm across your body, a slight bend in the elbow.',
      'Raise your arm out to the side until it reaches shoulder height.',
      'Lower back down with control.',
    ],
    techniqueTips: ['Keep the bend in your elbow constant throughout the movement.'],
    commonMistakes: ['Shrugging the shoulder up to help lift the weight', 'Raising above shoulder height'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-cable-woodchopper',
    name: 'Cable Woodchopper',
    category: 'functional',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['cable'],
    instructions: [
      'Set a pulley to the top position and stand side-on, gripping the handle with both hands.',
      'Pull the handle diagonally down and across your body, rotating your torso and hips as you go.',
      'Finish with the handle near your opposite hip.',
      'Return with control to the starting position and complete all reps before switching sides.',
    ],
    techniqueTips: ['Rotate through your whole torso and hips, not just your arms.'],
    commonMistakes: ['Only using the arms instead of rotating the core', 'Using momentum to yank the weight through'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    primarySpecificMuscles: ['lats'],
    equipment: ['cable'],
    instructions: [
      'Sit at the pulldown station and secure your thighs under the pad, gripping the bar wider than shoulder-width.',
      'Lean back very slightly and pull the bar down to your upper chest.',
      'Squeeze your shoulder blades together at the bottom.',
      'Let the bar rise back up with control to full arm extension.',
    ],
    techniqueTips: ['Drive your elbows down and back rather than pulling with your hands.'],
    commonMistakes: ['Leaning back excessively and turning it into a row', 'Using momentum to jerk the bar down'],
    placeholderToken: 'pullup',
  }),
  lib({
    id: 'ex-cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'strength',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back'],
    equipment: ['cable'],
    instructions: [
      'Attach a rope to a low pulley and stand facing away from the machine, straddling the cable with the rope between your legs.',
      'Hinge forward at the hips with soft knees, letting the rope pull your arms back between your legs.',
      'Drive your hips forward to stand tall, squeezing your glutes at the top.',
      'Control the weight back down into the next hinge.',
    ],
    techniqueTips: ['This is a hip hinge, not a squat — keep the movement coming from the hips.'],
    commonMistakes: ['Squatting the movement instead of hinging', 'Rounding the lower back at the bottom'],
    placeholderToken: 'kettlebell',
  }),
  lib({
    id: 'ex-hammer-chest-press',
    name: 'Hammer Strength Chest Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['machine'],
    notes: 'Plate-loaded, independent (iso-lateral) arms — each side moves on its own path.',
    instructions: [
      'Set the seat height so the handles line up with your mid-chest.',
      'Grip a handle in each hand with your back flat against the pad.',
      'Press both handles forward to full extension without locking out aggressively.',
      'Return with control until the handles are back at your chest.',
    ],
    techniqueTips: ['Press evenly with both arms so the independent handles travel together.'],
    commonMistakes: ['Flaring the elbows out to 90 degrees', 'Arching off the seat pad to add range of motion'],
    placeholderToken: 'bench',
  }),
  lib({
    id: 'ex-hammer-decline-press',
    name: 'Hammer Strength Decline Chest Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    primarySpecificMuscles: ['chest_lower'],
    equipment: ['machine'],
    notes: 'Plate-loaded machine; targets the lower chest with a downward pressing angle.',
    instructions: [
      'Adjust the seat so the handles sit level with your lower chest.',
      'Grip a handle in each hand, keeping your shoulder blades pulled back and down.',
      'Press forward and slightly down until your arms are extended.',
      'Return with control to the starting position.',
    ],
    techniqueTips: ['Keep your wrists stacked over your elbows throughout the press.'],
    commonMistakes: ['Bouncing the handles at the bottom of each rep', 'Pressing unevenly between arms'],
    placeholderToken: 'bench',
  }),
  lib({
    id: 'ex-hammer-shoulder-press',
    name: 'Hammer Strength Shoulder Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    primarySpecificMuscles: ['front_delts'],
    equipment: ['machine'],
    notes: 'Plate-loaded, independent arms.',
    instructions: [
      'Set the seat so the handles start level with your shoulders.',
      'Grip a handle in each hand, back flat against the pad.',
      'Press both handles up until your arms are extended without locking out hard.',
      'Lower back down with control to shoulder height.',
    ],
    techniqueTips: ['Keep your core braced and avoid arching your lower back off the pad.'],
    commonMistakes: ['Pressing unevenly, letting one arm lead', 'Shrugging the shoulders up at the top'],
    placeholderToken: 'press',
  }),
  lib({
    id: 'ex-hammer-high-row',
    name: 'Hammer Strength High Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    primarySpecificMuscles: ['traps'],
    secondarySpecificMuscles: ['rear_delts'],
    equipment: ['machine'],
    notes: 'Plate-loaded machine, chest-supported with a high pulling angle for the upper back.',
    instructions: [
      'Set the chest pad height and sit or kneel facing it, gripping a handle in each hand.',
      'Start with your arms extended in front of you.',
      'Pull both handles back, driving your elbows up and out, squeezing your upper back.',
      'Extend back out with control.',
    ],
    techniqueTips: ['Keep your chest pinned to the pad throughout — don’t use body English to move more weight.'],
    commonMistakes: ['Shrugging instead of pulling with the back', 'Using a partial range of motion'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-hammer-low-row',
    name: 'Hammer Strength Low Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    primarySpecificMuscles: ['lats'],
    equipment: ['machine'],
    notes: 'Plate-loaded machine, chest-supported with a low pulling angle for the mid-back and lats.',
    instructions: [
      'Set the chest pad height and sit facing it, gripping a handle in each hand at a lower angle.',
      'Start with arms extended forward.',
      'Pull both handles back toward your hips, driving your elbows straight back.',
      'Extend back out with control to the starting position.',
    ],
    techniqueTips: ['Keep your chest against the pad and avoid rocking to generate momentum.'],
    commonMistakes: ['Rounding the shoulders forward at the start', 'Yanking the weight with momentum'],
    placeholderToken: 'row',
  }),
  lib({
    id: 'ex-hammer-leg-press',
    name: 'Hammer Strength Leg Press',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    notes: 'Plate-loaded, independent (iso-lateral) leg press.',
    instructions: [
      'Sit in the machine with your feet shoulder-width apart on the platform, mid-foot centred.',
      'Release the safeties and lower the platform until your knees reach roughly 90 degrees.',
      'Press through your whole foot to extend your legs without locking your knees out hard.',
      'Lower back down with control and repeat.',
    ],
    techniqueTips: ['Keep your lower back flat against the pad — don’t let your hips round up off the seat at the bottom.'],
    commonMistakes: ['Locking the knees out hard at the top', 'Letting the knees cave inward under load'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-leg-curl-machine',
    name: 'Seated Leg Curl',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    primarySpecificMuscles: ['hamstrings_medial', 'hamstrings_lateral'],
    equipment: ['machine'],
    instructions: [
      'Sit in the machine with the back pad adjusted and the lever pad resting just above your heels.',
      'Grip the handles and brace your thighs against the leg pad.',
      'Curl your heels down and back, bending your knees through the full range.',
      'Return with control to the starting position.',
    ],
    techniqueTips: ['Point your toes toward your shins to keep the calves from taking over the movement.'],
    commonMistakes: ['Using momentum by swinging the legs', 'Lifting the hips off the seat'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-leg-extension-machine',
    name: 'Leg Extension',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    instructions: [
      'Sit in the machine with the back pad adjusted and the lever pad resting on the front of your shins.',
      'Grip the handles and sit tall.',
      'Extend your knees to raise the pad until your legs are straight.',
      'Lower back down with control to the starting position.',
    ],
    techniqueTips: ['Pause briefly at the top and control the descent rather than letting the weight drop.'],
    commonMistakes: ['Using momentum to kick the weight up', 'Only using the bottom half of the range of motion'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-smith-machine-squat',
    name: 'Smith Machine Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    instructions: [
      'Set the bar at upper-back height and step under it, unracking by rotating it out of the hooks.',
      'Set your feet slightly in front of your hips since the bar path is fixed vertically.',
      'Lower under control until your thighs are at least parallel to the floor.',
      'Drive back up through your whole foot to standing.',
    ],
    techniqueTips: ['Because the bar path is fixed, let your hips travel back naturally rather than forcing a straight-up-and-down squat.'],
    commonMistakes: ['Placing the feet directly under the bar, which strains the knees', 'Rushing the unrack/re-rack twist'],
    placeholderToken: 'squat',
  }),
  lib({
    id: 'ex-band-hamstring-stretch',
    name: 'Band-Assisted Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves', 'lower_back'],
    equipment: ['resistance_band'],
    instructions: [
      'Lie on your back and loop a light band around the ball of one foot.',
      'Keeping that leg straight, pull gently with the band to draw it toward your chest.',
      'Hold, feeling a stretch through the back of the thigh, then switch sides.',
    ],
    techniqueTips: ['Keep the other leg flat on the floor to isolate the stretch.'],
    commonMistakes: ['Bending the knee of the leg being stretched', 'Yanking the band instead of easing into it'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-chest-stretch',
    name: 'Band Chest Stretch',
    category: 'mobility',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['resistance_band'],
    instructions: [
      'Anchor a light band at chest height behind you and hold an end in each hand.',
      'Step forward until you feel tension, then let your arms drift slightly back and open across your chest.',
      'Hold, breathing steadily, feeling the stretch across the front of the shoulders and chest.',
    ],
    techniqueTips: ['Keep a slight bend in the elbows rather than locking them out.'],
    commonMistakes: ['Stepping so far forward the stretch becomes painful rather than comfortable tension'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-triceps-stretch',
    name: 'Band Overhead Triceps Stretch',
    category: 'mobility',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['resistance_band'],
    instructions: [
      'Hold one end of a light band overhead with one hand and let the other end hang down your back.',
      'Reach behind your lower back with the opposite hand and grip the band.',
      'Gently pull down with the lower hand to deepen the stretch in the overhead arm, then switch sides.',
    ],
    techniqueTips: ['Keep the overhead elbow pointing up rather than out to the side.'],
    commonMistakes: ['Pulling hard and fast instead of easing into the stretch'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-quad-stretch',
    name: 'Band-Assisted Quad Stretch',
    category: 'mobility',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['resistance_band'],
    instructions: [
      'Loop a light band around one ankle and anchor or hold the other end behind you at hip height.',
      'Standing tall, let the band gently draw the heel toward your glute.',
      'Hold, feeling a stretch down the front of the thigh, then switch sides.',
    ],
    techniqueTips: ['Keep your knees close together and hips level throughout.'],
    commonMistakes: ['Arching the lower back to fake more range of motion'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-lat-stretch',
    name: 'Band Lat Stretch',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: ['resistance_band'],
    instructions: [
      'Anchor a light band at head height and grip it with one hand, arm extended overhead.',
      'Step back and sink your hips away from the anchor, letting the band pull your arm and side into a stretch.',
      'Hold, then switch sides.',
    ],
    techniqueTips: ['Keep a slight bend in the knees and let the stretch come from your hips, not your lower back.'],
    commonMistakes: ['Rounding the lower back instead of hinging from the hips'],
    placeholderToken: 'stretch',
  }),
  lib({
    id: 'ex-band-calf-stretch',
    name: 'Band-Assisted Calf Stretch',
    category: 'mobility',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['resistance_band'],
    instructions: [
      'Sit with the target leg extended and loop a light band around the ball of that foot.',
      'Holding an end in each hand, gently pull the toes back toward your shin.',
      'Hold, feeling a stretch through the calf, then switch sides.',
    ],
    techniqueTips: ['Keep the knee straight but not locked to feel the stretch through the full calf.'],
    commonMistakes: ['Pulling in short jerky tugs instead of a steady, sustained hold'],
    placeholderToken: 'stretch',
  }),
]
