import { db } from '../db'
import type { Table } from 'dexie'

/**
 * One entry per synced Dexie table. `toRemote`/`fromRemote` translate between the
 * app's camelCase local shape and the snake_case Postgres columns; nested JSON
 * (sets, exercises, activities, pattern, …) is passed through untouched since it's
 * stored as opaque `jsonb` and never queried column-by-column on the server.
 *
 * `singleton` tables (profile, settings) are keyed locally by the fixed id
 * `"singleton"` but remotely by the user's own auth id — every other table uses
 * the same client-generated id on both sides.
 */
export interface SyncTableConfig {
  dexieTable: string
  remoteTable: string
  singleton: boolean
  localTable: () => Table<Record<string, unknown>, string>
  toRemote: (row: Record<string, unknown>, userId: string) => Record<string, unknown>
  fromRemote: (row: Record<string, unknown>, userId: string) => Record<string, unknown>
}

const passthroughArray = (v: unknown) => v ?? []

export const SYNC_TABLE_CONFIGS: SyncTableConfig[] = [
  {
    dexieTable: 'customExercises',
    remoteTable: 'custom_exercises',
    singleton: false,
    localTable: () => db.customExercises as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      name: r.name,
      category: r.category,
      primary_muscles: passthroughArray(r.primaryMuscles),
      secondary_muscles: passthroughArray(r.secondaryMuscles),
      equipment: passthroughArray(r.equipment),
      instructions: passthroughArray(r.instructions),
      technique_tips: passthroughArray(r.techniqueTips),
      common_mistakes: passthroughArray(r.commonMistakes),
      media: r.media,
      notes: r.notes ?? null,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      source: 'custom',
      name: r.name,
      category: r.category,
      primaryMuscles: passthroughArray(r.primary_muscles),
      secondaryMuscles: passthroughArray(r.secondary_muscles),
      equipment: passthroughArray(r.equipment),
      instructions: passthroughArray(r.instructions),
      techniqueTips: passthroughArray(r.technique_tips),
      commonMistakes: passthroughArray(r.common_mistakes),
      media: r.media,
      notes: r.notes ?? undefined,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'routines',
    remoteTable: 'routines',
    singleton: false,
    localTable: () => db.routines as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      name: r.name,
      description: r.description ?? null,
      notes: r.notes ?? null,
      warmup: r.warmup,
      main: r.main,
      cooldown: r.cooldown,
      default_rest_seconds: r.defaultRestSeconds,
      archived: r.archived,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      type: 'workout',
      name: r.name,
      description: r.description ?? undefined,
      notes: r.notes ?? undefined,
      warmup: r.warmup,
      main: r.main,
      cooldown: r.cooldown,
      defaultRestSeconds: r.default_rest_seconds,
      archived: r.archived,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'recoveryRoutines',
    remoteTable: 'recovery_routines',
    singleton: false,
    localTable: () => db.recoveryRoutines as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      name: r.name,
      description: r.description ?? null,
      instructions: r.instructions ?? null,
      activities: passthroughArray(r.activities),
      estimated_duration_minutes: r.estimatedDurationMinutes ?? null,
      archived: r.archived,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      type: 'recovery',
      name: r.name,
      description: r.description ?? undefined,
      instructions: r.instructions ?? undefined,
      activities: passthroughArray(r.activities),
      estimatedDurationMinutes: r.estimated_duration_minutes ?? undefined,
      archived: r.archived,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'schedules',
    remoteTable: 'schedules',
    singleton: false,
    localTable: () => db.schedules as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      name: r.name,
      start_date: r.startDate,
      end_date: r.endDate ?? null,
      pattern: r.pattern,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      name: r.name,
      startDate: r.start_date,
      endDate: r.end_date ?? undefined,
      pattern: r.pattern,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'occurrenceOverrides',
    remoteTable: 'occurrence_overrides',
    singleton: false,
    localTable: () => db.occurrenceOverrides as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      schedule_id: r.scheduleId,
      original_date: r.originalDate,
      new_date: r.newDate ?? null,
      status: r.status ?? null,
      assignment_override: r.assignmentOverride ?? null,
      session_id: r.sessionId ?? null,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      scheduleId: r.schedule_id,
      originalDate: r.original_date,
      newDate: r.new_date ?? undefined,
      status: r.status ?? undefined,
      assignmentOverride: r.assignment_override ?? undefined,
      sessionId: r.session_id ?? undefined,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'workoutSessions',
    remoteTable: 'workout_sessions',
    singleton: false,
    localTable: () => db.workoutSessions as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      kind: 'workout',
      origin: r.origin,
      schedule_id: r.scheduleId ?? null,
      occurrence_date: r.occurrenceDate ?? null,
      routine_template_id: r.routineTemplateId ?? null,
      name: r.name,
      status: r.status,
      scheduled_date: r.scheduledDate,
      started_at: r.startedAt ?? null,
      finished_at: r.finishedAt ?? null,
      pause_intervals: passthroughArray(r.pauseIntervals),
      warmup: r.warmup ?? null,
      main: passthroughArray(r.main),
      cooldown: r.cooldown ?? null,
      notes: r.notes ?? null,
      review: r.review ?? null,
      rest_timer_ends_at: r.restTimerEndsAt ?? null,
      rest_timer_enabled: r.restTimerEnabled ?? null,
      rest_timer_seconds: r.restTimerSeconds ?? null,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      kind: 'workout',
      origin: r.origin,
      scheduleId: r.schedule_id ?? undefined,
      occurrenceDate: r.occurrence_date ?? undefined,
      routineTemplateId: r.routine_template_id ?? undefined,
      name: r.name,
      status: r.status,
      scheduledDate: r.scheduled_date,
      startedAt: r.started_at ?? undefined,
      finishedAt: r.finished_at ?? undefined,
      pauseIntervals: passthroughArray(r.pause_intervals),
      warmup: r.warmup ?? undefined,
      main: passthroughArray(r.main),
      cooldown: r.cooldown ?? undefined,
      notes: r.notes ?? undefined,
      review: r.review ?? undefined,
      restTimerEndsAt: r.rest_timer_ends_at ?? undefined,
      restTimerEnabled: r.rest_timer_enabled ?? undefined,
      restTimerSeconds: r.rest_timer_seconds ?? undefined,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'recoverySessions',
    remoteTable: 'recovery_sessions',
    singleton: false,
    localTable: () => db.recoverySessions as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      kind: 'recovery',
      origin: r.origin,
      schedule_id: r.scheduleId ?? null,
      occurrence_date: r.occurrenceDate ?? null,
      routine_template_id: r.routineTemplateId ?? null,
      name: r.name,
      status: r.status,
      scheduled_date: r.scheduledDate,
      started_at: r.startedAt ?? null,
      finished_at: r.finishedAt ?? null,
      activities: passthroughArray(r.activities),
      notes: r.notes ?? null,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      kind: 'recovery',
      origin: r.origin,
      scheduleId: r.schedule_id ?? undefined,
      occurrenceDate: r.occurrence_date ?? undefined,
      routineTemplateId: r.routine_template_id ?? undefined,
      name: r.name,
      status: r.status,
      scheduledDate: r.scheduled_date,
      startedAt: r.started_at ?? undefined,
      finishedAt: r.finished_at ?? undefined,
      activities: passthroughArray(r.activities),
      notes: r.notes ?? undefined,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'restDaySessions',
    remoteTable: 'rest_day_sessions',
    singleton: false,
    localTable: () => db.restDaySessions as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      kind: 'rest',
      schedule_id: r.scheduleId ?? null,
      occurrence_date: r.occurrenceDate ?? null,
      scheduled_date: r.scheduledDate,
      status: r.status,
      notes: r.notes ?? null,
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      kind: 'rest',
      scheduleId: r.schedule_id ?? undefined,
      occurrenceDate: r.occurrence_date ?? undefined,
      scheduledDate: r.scheduled_date,
      status: r.status,
      notes: r.notes ?? undefined,
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'weightEntries',
    remoteTable: 'weight_entries',
    singleton: false,
    localTable: () => db.weightEntries as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({ id: r.id, user_id: userId, value_kg: r.valueKg, recorded_at: r.recordedAt }),
    fromRemote: (r) => ({ id: r.id, valueKg: r.value_kg, recordedAt: r.recorded_at }),
  },
  {
    dexieTable: 'heightEntries',
    remoteTable: 'height_entries',
    singleton: false,
    localTable: () => db.heightEntries as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({ id: r.id, user_id: userId, value_cm: r.valueCm, recorded_at: r.recordedAt }),
    fromRemote: (r) => ({ id: r.id, valueCm: r.value_cm, recordedAt: r.recorded_at }),
  },
  {
    dexieTable: 'personalEvents',
    remoteTable: 'personal_events',
    singleton: false,
    localTable: () => db.personalEvents as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: r.id,
      user_id: userId,
      title: r.title,
      notes: r.notes ?? null,
      color: r.color,
      start_date: r.startDate,
      end_date: r.endDate ?? null,
      recurrence: r.recurrence,
      excluded_dates: passthroughArray(r.excludedDates),
      created_at: r.createdAt,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: r.id,
      title: r.title,
      notes: r.notes ?? undefined,
      color: r.color,
      startDate: r.start_date,
      endDate: r.end_date ?? undefined,
      recurrence: r.recurrence,
      excludedDates: passthroughArray(r.excluded_dates),
      createdAt: r.created_at,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'profile',
    remoteTable: 'profiles',
    singleton: true,
    localTable: () => db.profile as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: userId,
      name: r.name,
      dob: r.dob ?? null,
      weight_unit: r.weightUnit,
      height_unit: r.heightUnit,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: 'singleton',
      name: r.name,
      dob: r.dob ?? undefined,
      weightUnit: r.weight_unit,
      heightUnit: r.height_unit,
      updatedAt: r.updated_at,
    }),
  },
  {
    dexieTable: 'settings',
    remoteTable: 'settings',
    singleton: true,
    localTable: () => db.settings as unknown as Table<Record<string, unknown>, string>,
    toRemote: (r, userId) => ({
      id: userId,
      streak: r.streak,
      default_rest_seconds: r.defaultRestSeconds,
      sound_enabled: r.soundEnabled,
      vibration_enabled: r.vibrationEnabled,
      show_exercise_media: r.showExerciseMedia,
      theme: r.theme,
      notifications_enabled: r.notificationsEnabled,
      rest_timer_enabled: r.restTimerEnabled,
      calendar_colors: r.calendarColors,
      updated_at: r.updatedAt,
    }),
    fromRemote: (r) => ({
      id: 'singleton',
      streak: r.streak,
      defaultRestSeconds: r.default_rest_seconds,
      soundEnabled: r.sound_enabled,
      vibrationEnabled: r.vibration_enabled,
      showExerciseMedia: r.show_exercise_media,
      theme: r.theme,
      notificationsEnabled: r.notifications_enabled,
      restTimerEnabled: r.rest_timer_enabled ?? true,
      calendarColors: r.calendar_colors ?? undefined,
      updatedAt: r.updated_at,
    }),
  },
]

export const SYNC_CONFIG_BY_TABLE: Record<string, SyncTableConfig> = Object.fromEntries(
  SYNC_TABLE_CONFIGS.map((c) => [c.dexieTable, c]),
)
